passageidentity/passage-node

- change/@passageidentity-passage-node-5524b98c-be4e-4e30-bb89-94cadf77ecb7.json
- src/classes/User.ts
- src/types/App.ts
-   update App fields
-   -required_identifier
-   -require_email_verification
-   +require_identifier_verification
-   add phone_verified to User
This aligns the SDK with the API changes made to simplify identifier verification.
This is a breaking change, as it removes 2 fields.
> sc-1717/update sdks with model changes

- testServer.ts
- tests/test-suite.test.ts
JWT authentication tests imrpoved: 
- make sure to test HEADER auth JWT authentication
- add more robust tests around invalid_tokens
> PSG-1301: SDK tests to test both header and cookie auth for all SDKs

- change/@passageidentity-passage-node-258b5071-7b2f-498c-acfa-037a5e7abcd6.json
- src/types/App.ts
Provides the ability to get and configure Auth Fallback App Properties.
> Add Auth Fallback Method Properties

- CHANGELOG.json
- CHANGELOG.md
- change/@passageidentity-passage-node-17c52c64-27c9-460e-9235-05df1e1e6116.json
- change/@passageidentity-passage-node-9def398b-5080-44e7-b4a1-8284ae3f4485.json
- change/@passageidentity-passage-node-a87e517e-ce2b-40c2-ab81-4fadfd6124d3.json
- change/@passageidentity-passage-node-df785dc0-183d-4fc8-906b-3f1c42126982.json
- package-lock.json
- package.json
Beachball failed to update main with changes that should have been included. This gets the repo and npm back in sync.
> update main with changes beachball should have

- CHANGELOG.json
- CHANGELOG.md
- change/@passageidentity-passage-node-76c4cfa0-ce07-4f17-a191-5b46333694b9.json
- change/@passageidentity-passage-node-9d46d8e5-fb94-4aef-9b46-56c0c9f9d189.json
- change/@passageidentity-passage-node-a87e517e-ce2b-40c2-ab81-4fadfd6124d3.json
- package-lock.json
- package.json
Sync repo again to npm version 2.5.1 since beachball is still behaving weirdly.
> Sync Repo with NPM

- .github/workflows/deploy.yml
- change/@passageidentity-passage-node-d871e18f-7b92-4a04-8523-873e8fdad2b2.json
- package-lock.json
- package.json
Include the token flag when calling beachball:publish and update beachball version to latest.
> Update how we pass beachball token

- LICENSE
- README.md
- change/@passageidentity-passage-node-2af55c94-db86-4e6c-9599-7f0b94e62114.json
- package.json
Updates README, LICENCE, and package.json files.
> Psg 4897 use repo templates

- change/@passageidentity-passage-node-43912fbd-d95f-4144-b864-9f3511d1b9a8.json
- src/classes/Passage.ts
- src/classes/User.ts
- src/types/PassageConfig.ts
- src/utils/apiConfiguration.ts
Per customer request, adding support for passing in an external fetch api implementation. Optional parameter, if none is provided then node-fetch will be the default.
Verified functional by testing passing in regular `fetch` in test project.
> Add Support For External Fetch API

- src/classes/Auth/Auth.ts
Add audience validation. To enable backwards compatibility with current token format I'm checking to see if the `aud` is an array first and then validating the app ID is present in the `aud` array.
Tested locally against a UAT app and token.
> feat: Add Audience Validation

- .github/workflows/release.yml
> ci: remove type specification so gha will use release please config file

- src/classes/User/User.spec.ts
- src/classes/User/User.ts
Minor error string update to match other SDKs.
> fix: Use consistent user not found error

- src/classes/Auth/Auth.ts
- src/classes/User/User.ts
- Adds parameter guards for all Auth and User operations to simplify input checks that can be done before making a network request
- Guards for the deprecated create magic link method are not added because it relies on default values from our API to execute without exception, so adding exceptions here would be a breaking change
- Guards for the new create magic link method are not added because the type safety prohibits incorrect values
> feat: add parameter guards

- src/classes/Auth/Auth.ts
- Sets the channel when identifier is email or phone to their respective channels
- Also moves the magic link api initialization to the constructor so it isn't created on every call
> chore: set create magic link channel when identifier is email or phone

- .github/workflows/release.yml
> ci: use npm gh

- release-please-config.json
[ref](https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json#:~:text=%22include%2Dcomponent%2Din%2Dtag%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22description%22%3A%20%22When%20tagging%20a%20release%2C%20include%20the%20component%20name%20as%20part%20of%20the%20tag.%20Defaults%20to%20%60true%60.%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22boolean%22%0A%20%20%20%20%20%20%20%20%7D%2C)
> build: remove component from git tag

- generate.sh
- src/classes/Auth/Auth.ts
- src/classes/Passage/Passage.ts
- src/generated/models/AppInfo.ts
- src/generated/models/AppleUserSocialConnection.ts
- src/generated/models/AuthMethods.ts
- src/generated/models/CreateMagicLinkRequest.ts
- src/generated/models/CreateUserRequest.ts
- src/generated/models/ElementCustomization.ts
- src/generated/models/GithubUserSocialConnection.ts
- src/generated/models/GoogleUserSocialConnection.ts
- src/generated/models/ListPaginatedUsersItem.ts
- src/generated/models/ListPaginatedUsersResponse.ts
- src/generated/models/MagicLink.ts
- src/generated/models/MagicLinkAuthMethod.ts
- src/generated/models/MagicLinkResponse.ts
- src/generated/models/OtpAuthMethod.ts
- src/generated/models/UpdateUserRequest.ts
- src/generated/models/UserInfo.ts
- src/generated/models/UserMetadataField.ts
- src/generated/models/UserRecentEvent.ts
- src/generated/models/WebAuthnDevices.ts
- updates codegen options to transform json props from snake_case to camelCase
> feat!: codegen models now use camelCase props

- package.json
> build: drop support for node v16

- src/classes/Auth/Auth.ts
> feat: removes auth origin comparison from jwt audience validation

- generate.sh
- src/classes/Auth/types.ts
- src/classes/PassageBase/PassageBase.ts
- src/classes/PassageError/index.ts
- src/classes/PassageError/types.ts
- src/classes/User/User.ts
- src/classes/User/types.ts
- src/generated/.openapi-generator/FILES
- src/generated/apis/UsersApi.ts
- src/generated/models/CreateUserArgs.ts
- src/generated/models/PassageUser.ts
- src/generated/models/UpdateUserArgs.ts
- src/generated/models/UserResponse.ts
- src/generated/models/index.ts
- updates generate script with configs to rename codegen'd models so we don't have to manually alias them
- ran script against the latest mgmt-sdk openapi specs to update models
- removed exports that didn't need to be exposed to the developer (breaking, will be marked as such in footer message of squash commit on merge)
> build: add config to rename codegen models

- src/classes/Passage/Passage.spec.ts
- src/classes/Passage/Passage.ts
- src/classes/Passage/types.ts
- changes `appID` to `appId` to be have a more idiomatic naming convention in TS
> feat!: change appID parameter name in Passage constructor to appId

- README.md
updates README code blocks to use new constructor signature
> chore: update readme code blocks
